### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by oeldisplay** [cryptovoxels/foxus-releases#1]
My foxus camera makes a chime when plugged in, I original sideloaded the github app and it would just show a black wall with text asking to give permission in "VRUI" i figured out pressing "b" makes a pop-up. I clicked to allow permission pop-up, nothing pops-up just the black wall. I just updated my Quest2 and now the app just crashes, no text or pop-up or anything.

**Comment by oeldisplay** [comment]
update [0.9.5] fixed this.

**Comment by BryGuyD** [comment]
Make sure to close this and mark it as resolved
